Style/Documentation:
  Exclude:
    - 'compat/**/*.rb'
    - 'extend/**/*.rb'
    - 'cmd/**/*.rb'
    - 'dev-cmd/**/*.rb'
    - 'test/**/*.rb'
    - 'cask/macos.rb'
    - 'cli/args.rb'
    - 'cli/parser.rb'
    - 'global.rb'
    - 'keg_relocate.rb'
    - 'os/linux/global.rb'
    - 'os/mac/architecture_list.rb'
    - 'os/mac/keg.rb'
    - 'reinstall.rb'
    - 'software_spec.rb'
    - 'upgrade.rb'
    - 'utils.rb'
    - 'utils/fork.rb'
    - 'utils/gems.rb'
    - 'utils/popen.rb'
    - 'utils/shell.rb'
    - 'version.rb'
